simulation_config:
  data_folder: to be overwritten              # directory to save simulation log
  start_generation_ind: 0                     # start generation index
  end_generation_ind: 10                      # end generation index
  generation_digits_num: 7                    # use how many digits to represent generation index
  process_num: 10                             # process number for multi-processing
  simulation_length: 50000                    # max simulation length for each fish

evolution_config:
  connection_mutation_rate: 0.01
  neuron_mutation_rate: 0.01
  population_size: 1000
  turnover_rate: 0.6
  life_span_hard_threshold: 0
  movement_hard_threshold: 0

brain_config:
  eye_layer:
    eye_set: FOUR_EYES
    input_types: 
    - terrain
    - food
    gain: 1.
    baseline_rate: 0.0
    refractory_period: 1.2

  hidden_layers:
    neuron_nums:
    - 8
    baseline_rate: 0.005
    refractory_period: 1.2

  muscle_layer:
    muscle_set: FOUR_MUSCLES
    baseline_rate: 0.001
    refractory_period: 10.

  connection_0_1: 
    connection_type: full
    amplitude: 0.01
    latency: 3
    rise_time: 2
    decay_time: 5

  connection_1_2: 
    connection_type: full
    amplitude: 0.01
    latency: 3
    rise_time: 2
    decay_time: 5

fish_config:
  food_rate: 20.0
  land_penalty_rate: 0.5
  max_health: 20.0
  health_decay_rate: 0.01
  move_penalty_rate: 0.001
  mother_name: null
  name: null

brain_mutation_config:
  eye_gain_r: null                          # eye gain range
  eye_bl_r:                                 # eye baseline range
  - -0.1
  - 0.1
  eye_rp_r: null                            # eye refractory period rang
  
  neuron_bl_r:                              # hidden neuron baseline range
  - -0.1
  - 0.1
  neuron_rp_r: null                         # hidden neuron refractory period range

  muscle_bl_r:                              # muscle baseline range
  - -0.1
  - 0.1
  muscle_rp_r: null                         # muscle refractory period range
  
  connection_a_r:                           # connection amplitude range
  - -1
  - 1
  connection_l_r: null                      # connection latency range
  connection_rt_r: null                     # connection rise time range
  connection_dt_r: null                     # connection decay time range
  
terrain_config:
  food_num: 100                             # number of food
  sea_portion: 0.7                          # portion of the sea
  terrain_filter_sigma: 3.0
  terrain_size:                             # shape of terrain                     
  - 64
  - 64
