# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_viewer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulationViewer(object):
    def setupUi(self, SimulationViewer):
        SimulationViewer.setObjectName("SimulationViewer")
        SimulationViewer.resize(981, 871)
        self.centralwidget = QtWidgets.QWidget(SimulationViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.FishLabel = QtWidgets.QLabel(self.centralwidget)
        self.FishLabel.setGeometry(QtCore.QRect(641, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FishLabel.setFont(font)
        self.FishLabel.setObjectName("FishLabel")
        self.SimulationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SimulationComboBox.setGeometry(QtCore.QRect(141, 80, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulationComboBox.setFont(font)
        self.SimulationComboBox.setObjectName("SimulationComboBox")
        self.SimulationLabel = QtWidgets.QLabel(self.centralwidget)
        self.SimulationLabel.setGeometry(QtCore.QRect(21, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulationLabel.setFont(font)
        self.SimulationLabel.setObjectName("SimulationLabel")
        self.ChooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseFileButton.setGeometry(QtCore.QRect(21, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ChooseFileButton.setFont(font)
        self.ChooseFileButton.setObjectName("ChooseFileButton")
        self.FilePathBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.FilePathBrowser.setGeometry(QtCore.QRect(211, 20, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FilePathBrowser.setFont(font)
        self.FilePathBrowser.setObjectName("FilePathBrowser")
        self.TerrainLabel = QtWidgets.QLabel(self.centralwidget)
        self.TerrainLabel.setGeometry(QtCore.QRect(640, 400, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TerrainLabel.setFont(font)
        self.TerrainLabel.setObjectName("TerrainLabel")
        self.PlaySlider = QtWidgets.QSlider(self.centralwidget)
        self.PlaySlider.setGeometry(QtCore.QRect(110, 779, 511, 41))
        self.PlaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlaySlider.setObjectName("PlaySlider")
        self.PlayPauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayPauseButton.setGeometry(QtCore.QRect(20, 780, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PlayPauseButton.setFont(font)
        self.PlayPauseButton.setObjectName("PlayPauseButton")
        self.SimulationParamsLabel = QtWidgets.QLabel(self.centralwidget)
        self.SimulationParamsLabel.setGeometry(QtCore.QRect(640, 600, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulationParamsLabel.setFont(font)
        self.SimulationParamsLabel.setObjectName("SimulationParamsLabel")
        self.FishTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.FishTableWidget.setGeometry(QtCore.QRect(640, 130, 321, 251))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FishTableWidget.setFont(font)
        self.FishTableWidget.setShowGrid(False)
        self.FishTableWidget.setRowCount(6)
        self.FishTableWidget.setColumnCount(2)
        self.FishTableWidget.setObjectName("FishTableWidget")
        self.FishTableWidget.horizontalHeader().setVisible(False)
        self.FishTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.FishTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.FishTableWidget.verticalHeader().setVisible(False)
        self.SimulationTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.SimulationTableWidget.setGeometry(QtCore.QRect(640, 640, 321, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SimulationTableWidget.setFont(font)
        self.SimulationTableWidget.setShowGrid(False)
        self.SimulationTableWidget.setRowCount(4)
        self.SimulationTableWidget.setColumnCount(2)
        self.SimulationTableWidget.setObjectName("SimulationTableWidget")
        self.SimulationTableWidget.horizontalHeader().setVisible(False)
        self.SimulationTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.SimulationTableWidget.verticalHeader().setVisible(False)
        self.TerrainTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.TerrainTableWidget.setGeometry(QtCore.QRect(639, 440, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TerrainTableWidget.setFont(font)
        self.TerrainTableWidget.setShowGrid(False)
        self.TerrainTableWidget.setRowCount(3)
        self.TerrainTableWidget.setColumnCount(2)
        self.TerrainTableWidget.setObjectName("TerrainTableWidget")
        self.TerrainTableWidget.horizontalHeader().setVisible(False)
        self.TerrainTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.TerrainTableWidget.verticalHeader().setVisible(False)
        self.PlotBrainButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotBrainButton.setGeometry(QtCore.QRect(860, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PlotBrainButton.setFont(font)
        self.PlotBrainButton.setObjectName("PlotBrainButton")
        self.ClearFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearFileButton.setGeometry(QtCore.QRect(840, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClearFileButton.setFont(font)
        self.ClearFileButton.setObjectName("ClearFileButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 170, 601, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MovieLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MovieLayout.setContentsMargins(0, 0, 0, 0)
        self.MovieLayout.setObjectName("MovieLayout")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(20, 130, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.TimeTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.TimeTextBrowser.setGeometry(QtCore.QRect(90, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TimeTextBrowser.setFont(font)
        self.TimeTextBrowser.setStyleSheet("color: rgb(0, 85, 255);")
        self.TimeTextBrowser.setObjectName("TimeTextBrowser")
        self.HealthLabel = QtWidgets.QLabel(self.centralwidget)
        self.HealthLabel.setGeometry(QtCore.QRect(350, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HealthLabel.setFont(font)
        self.HealthLabel.setObjectName("HealthLabel")
        self.HealthTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.HealthTextBrowser.setGeometry(QtCore.QRect(430, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.HealthTextBrowser.setFont(font)
        self.HealthTextBrowser.setStyleSheet("color: rgb(155, 0, 0);")
        self.HealthTextBrowser.setObjectName("HealthTextBrowser")
        SimulationViewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SimulationViewer)
        self.statusbar.setObjectName("statusbar")
        SimulationViewer.setStatusBar(self.statusbar)

        self.retranslateUi(SimulationViewer)
        QtCore.QMetaObject.connectSlotsByName(SimulationViewer)

    def retranslateUi(self, SimulationViewer):
        _translate = QtCore.QCoreApplication.translate
        SimulationViewer.setWindowTitle(_translate("SimulationViewer", "SimulationViewer"))
        self.FishLabel.setText(_translate("SimulationViewer", "Fish:"))
        self.SimulationLabel.setText(_translate("SimulationViewer", "Simulation:"))
        self.ChooseFileButton.setText(_translate("SimulationViewer", "Choose File"))
        self.TerrainLabel.setText(_translate("SimulationViewer", "Terrain:"))
        self.PlayPauseButton.setText(_translate("SimulationViewer", "Play"))
        self.SimulationParamsLabel.setText(_translate("SimulationViewer", "Simulation:"))
        self.PlotBrainButton.setText(_translate("SimulationViewer", "Plot Brain"))
        self.ClearFileButton.setText(_translate("SimulationViewer", "Clear File"))
        self.TimeLabel.setText(_translate("SimulationViewer", "<html><head/><body><p><span style=\" color:#0055ff;\">Time:</span></p></body></html>"))
        self.HealthLabel.setText(_translate("SimulationViewer", "<html><head/><body><p><span style=\" color:#ff0000;\">Health:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SimulationViewer = QtWidgets.QMainWindow()
    ui = Ui_SimulationViewer()
    ui.setupUi(SimulationViewer)
    SimulationViewer.show()
    sys.exit(app.exec_())

