# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_viewer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationViewer(object):
    def setupUi(self, SimulationViewer):
        SimulationViewer.setObjectName("SimulationViewer")
        SimulationViewer.resize(951, 872)
        self.centralwidget = QtWidgets.QWidget(SimulationViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.FishLabel = QtWidgets.QLabel(self.centralwidget)
        self.FishLabel.setGeometry(QtCore.QRect(690, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FishLabel.setFont(font)
        self.FishLabel.setObjectName("FishLabel")
        self.SimulationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SimulationComboBox.setGeometry(QtCore.QRect(120, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SimulationComboBox.setFont(font)
        self.SimulationComboBox.setFrame(False)
        self.SimulationComboBox.setObjectName("SimulationComboBox")
        self.SimulationLabel = QtWidgets.QLabel(self.centralwidget)
        self.SimulationLabel.setGeometry(QtCore.QRect(11, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SimulationLabel.setFont(font)
        self.SimulationLabel.setObjectName("SimulationLabel")
        self.ChooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseFileButton.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ChooseFileButton.setFont(font)
        self.ChooseFileButton.setObjectName("ChooseFileButton")
        self.FilePathBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.FilePathBrowser.setGeometry(QtCore.QRect(131, 10, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FilePathBrowser.setFont(font)
        self.FilePathBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FilePathBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FilePathBrowser.setObjectName("FilePathBrowser")
        self.TerrainLabel = QtWidgets.QLabel(self.centralwidget)
        self.TerrainLabel.setGeometry(QtCore.QRect(690, 460, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TerrainLabel.setFont(font)
        self.TerrainLabel.setObjectName("TerrainLabel")
        self.PlaySlider = QtWidgets.QSlider(self.centralwidget)
        self.PlaySlider.setGeometry(QtCore.QRect(90, 810, 331, 31))
        self.PlaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlaySlider.setObjectName("PlaySlider")
        self.PlayPauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayPauseButton.setGeometry(QtCore.QRect(10, 811, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PlayPauseButton.setFont(font)
        self.PlayPauseButton.setObjectName("PlayPauseButton")
        self.SimulationParamsLabel = QtWidgets.QLabel(self.centralwidget)
        self.SimulationParamsLabel.setGeometry(QtCore.QRect(690, 640, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SimulationParamsLabel.setFont(font)
        self.SimulationParamsLabel.setObjectName("SimulationParamsLabel")
        self.FishTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.FishTableWidget.setGeometry(QtCore.QRect(690, 140, 251, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FishTableWidget.setFont(font)
        self.FishTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FishTableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FishTableWidget.setShowGrid(False)
        self.FishTableWidget.setRowCount(12)
        self.FishTableWidget.setColumnCount(2)
        self.FishTableWidget.setObjectName("FishTableWidget")
        self.FishTableWidget.horizontalHeader().setVisible(False)
        self.FishTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.FishTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.FishTableWidget.verticalHeader().setVisible(False)
        self.SimulationTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.SimulationTableWidget.setGeometry(QtCore.QRect(690, 680, 251, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SimulationTableWidget.setFont(font)
        self.SimulationTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SimulationTableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SimulationTableWidget.setShowGrid(False)
        self.SimulationTableWidget.setRowCount(5)
        self.SimulationTableWidget.setColumnCount(2)
        self.SimulationTableWidget.setObjectName("SimulationTableWidget")
        self.SimulationTableWidget.horizontalHeader().setVisible(False)
        self.SimulationTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.SimulationTableWidget.verticalHeader().setVisible(False)
        self.TerrainTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.TerrainTableWidget.setGeometry(QtCore.QRect(689, 500, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TerrainTableWidget.setFont(font)
        self.TerrainTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TerrainTableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TerrainTableWidget.setShowGrid(False)
        self.TerrainTableWidget.setRowCount(3)
        self.TerrainTableWidget.setColumnCount(2)
        self.TerrainTableWidget.setObjectName("TerrainTableWidget")
        self.TerrainTableWidget.horizontalHeader().setVisible(False)
        self.TerrainTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.TerrainTableWidget.verticalHeader().setVisible(False)
        self.PlotBrainButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotBrainButton.setGeometry(QtCore.QRect(740, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PlotBrainButton.setFont(font)
        self.PlotBrainButton.setAutoDefault(True)
        self.PlotBrainButton.setDefault(True)
        self.PlotBrainButton.setFlat(False)
        self.PlotBrainButton.setObjectName("PlotBrainButton")
        self.ClearFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearFileButton.setGeometry(QtCore.QRect(860, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ClearFileButton.setFont(font)
        self.ClearFileButton.setObjectName("ClearFileButton")
        self.TimeTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.TimeTextBrowser.setGeometry(QtCore.QRect(430, 810, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TimeTextBrowser.setFont(font)
        self.TimeTextBrowser.setStyleSheet("color: rgb(0, 85, 255);")
        self.TimeTextBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TimeTextBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TimeTextBrowser.setObjectName("TimeTextBrowser")
        self.HealthTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.HealthTextBrowser.setGeometry(QtCore.QRect(570, 810, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HealthTextBrowser.setFont(font)
        self.HealthTextBrowser.setStyleSheet("color: rgb(155, 0, 0);")
        self.HealthTextBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HealthTextBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.HealthTextBrowser.setObjectName("HealthTextBrowser")
        self.ToolbarWidget = QtWidgets.QWidget(self.centralwidget)
        self.ToolbarWidget.setGeometry(QtCore.QRect(10, 100, 661, 41))
        self.ToolbarWidget.setObjectName("ToolbarWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 661, 661))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MovieLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MovieLayout.setContentsMargins(0, 0, 0, 0)
        self.MovieLayout.setObjectName("MovieLayout")
        SimulationViewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SimulationViewer)
        self.statusbar.setObjectName("statusbar")
        SimulationViewer.setStatusBar(self.statusbar)

        self.retranslateUi(SimulationViewer)
        QtCore.QMetaObject.connectSlotsByName(SimulationViewer)

    def retranslateUi(self, SimulationViewer):
        _translate = QtCore.QCoreApplication.translate
        SimulationViewer.setWindowTitle(
            _translate("SimulationViewer", "SimulationViewer")
        )
        self.FishLabel.setText(_translate("SimulationViewer", "Fish:"))
        self.SimulationLabel.setText(_translate("SimulationViewer", "Simulation:"))
        self.ChooseFileButton.setText(_translate("SimulationViewer", "Choose File"))
        self.TerrainLabel.setText(_translate("SimulationViewer", "Terrain:"))
        self.PlayPauseButton.setText(_translate("SimulationViewer", "Play"))
        self.SimulationParamsLabel.setText(
            _translate("SimulationViewer", "Simulation:")
        )
        self.PlotBrainButton.setText(_translate("SimulationViewer", "Plot Brain"))
        self.ClearFileButton.setText(_translate("SimulationViewer", "Clear File"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    SimulationViewer = QtWidgets.QMainWindow()
    ui = Ui_SimulationViewer()
    ui.setupUi(SimulationViewer)
    SimulationViewer.show()
    sys.exit(app.exec_())
