# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_viewer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulationViewer(object):
    def setupUi(self, SimulationViewer):
        SimulationViewer.setObjectName("SimulationViewer")
        SimulationViewer.resize(981, 721)
        self.centralwidget = QtWidgets.QWidget(SimulationViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.FishLabel = QtWidgets.QLabel(self.centralwidget)
        self.FishLabel.setGeometry(QtCore.QRect(641, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FishLabel.setFont(font)
        self.FishLabel.setObjectName("FishLabel")
        self.SimulationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SimulationComboBox.setGeometry(QtCore.QRect(141, 80, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulationComboBox.setFont(font)
        self.SimulationComboBox.setObjectName("SimulationComboBox")
        self.SimulationLabel = QtWidgets.QLabel(self.centralwidget)
        self.SimulationLabel.setGeometry(QtCore.QRect(21, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulationLabel.setFont(font)
        self.SimulationLabel.setObjectName("SimulationLabel")
        self.ChooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseFileButton.setGeometry(QtCore.QRect(21, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ChooseFileButton.setFont(font)
        self.ChooseFileButton.setObjectName("ChooseFileButton")
        self.FilePathBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.FilePathBrowser.setGeometry(QtCore.QRect(211, 20, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FilePathBrowser.setFont(font)
        self.FilePathBrowser.setObjectName("FilePathBrowser")
        self.TerrainLabel = QtWidgets.QLabel(self.centralwidget)
        self.TerrainLabel.setGeometry(QtCore.QRect(640, 350, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TerrainLabel.setFont(font)
        self.TerrainLabel.setObjectName("TerrainLabel")
        self.PlaySlider = QtWidgets.QSlider(self.centralwidget)
        self.PlaySlider.setGeometry(QtCore.QRect(110, 629, 511, 41))
        self.PlaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlaySlider.setObjectName("PlaySlider")
        self.PlayPauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayPauseButton.setGeometry(QtCore.QRect(24, 630, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PlayPauseButton.setFont(font)
        self.PlayPauseButton.setObjectName("PlayPauseButton")
        self.SimulationParamsLabel = QtWidgets.QLabel(self.centralwidget)
        self.SimulationParamsLabel.setGeometry(QtCore.QRect(640, 480, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulationParamsLabel.setFont(font)
        self.SimulationParamsLabel.setObjectName("SimulationParamsLabel")
        self.FishTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.FishTableWidget.setGeometry(QtCore.QRect(640, 130, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FishTableWidget.setFont(font)
        self.FishTableWidget.setObjectName("FishTableWidget")
        self.FishTableWidget.setColumnCount(0)
        self.FishTableWidget.setRowCount(0)
        self.SimulationTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.SimulationTableWidget.setGeometry(QtCore.QRect(640, 510, 321, 161))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SimulationTableWidget.setFont(font)
        self.SimulationTableWidget.setObjectName("SimulationTableWidget")
        self.SimulationTableWidget.setColumnCount(0)
        self.SimulationTableWidget.setRowCount(0)
        self.TerrainTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.TerrainTableWidget.setGeometry(QtCore.QRect(639, 380, 321, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TerrainTableWidget.setFont(font)
        self.TerrainTableWidget.setObjectName("TerrainTableWidget")
        self.TerrainTableWidget.setColumnCount(0)
        self.TerrainTableWidget.setRowCount(0)
        self.PlotBrainButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotBrainButton.setGeometry(QtCore.QRect(860, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PlotBrainButton.setFont(font)
        self.PlotBrainButton.setObjectName("PlotBrainButton")
        SimulationViewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SimulationViewer)
        self.statusbar.setObjectName("statusbar")
        SimulationViewer.setStatusBar(self.statusbar)

        self.retranslateUi(SimulationViewer)
        QtCore.QMetaObject.connectSlotsByName(SimulationViewer)

    def retranslateUi(self, SimulationViewer):
        _translate = QtCore.QCoreApplication.translate
        SimulationViewer.setWindowTitle(_translate("SimulationViewer", "SimulationViewer"))
        self.FishLabel.setText(_translate("SimulationViewer", "Fish:"))
        self.SimulationLabel.setText(_translate("SimulationViewer", "Simulation:"))
        self.ChooseFileButton.setText(_translate("SimulationViewer", "Choose File"))
        self.TerrainLabel.setText(_translate("SimulationViewer", "Terrain:"))
        self.PlayPauseButton.setText(_translate("SimulationViewer", "Play"))
        self.SimulationParamsLabel.setText(_translate("SimulationViewer", "Simulation:"))
        self.PlotBrainButton.setText(_translate("SimulationViewer", "Plot Brain"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SimulationViewer = QtWidgets.QMainWindow()
    ui = Ui_SimulationViewer()
    ui.setupUi(SimulationViewer)
    SimulationViewer.show()
    sys.exit(app.exec_())

