import unittest
import numpy as np
from littlefish.brain.brain import Connection


class TestConnection(unittest.TestCase):
    def setup(self):
        pass

    def test_connection_psp(self):
        connection = Connection(amplitude=10, latency=5, rise_time=5, decay_time=10)
        assert np.array_equal(
            connection.psp,
            np.array(
                [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    6.0,
                    8.0,
                    10.0,
                    9.0,
                    8.0,
                    7.0,
                    6.0,
                    5.0,
                    4.0,
                    3.0,
                    2.0,
                    1.0,
                    0.0,
                ]
            ),
        )

    def test_connection_act(self):
        simulation_length = 50
        connection = Connection(amplitude=10, latency=5, rise_time=5, decay_time=10)
        psp_waveforms = np.zeros((1, simulation_length))
        connection.act(t_point=2, postsynaptic_index=0, psp_waveforms=psp_waveforms)
        assert np.array_equal(
            psp_waveforms[0],
            np.array(
                [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    6.0,
                    8.0,
                    10.0,
                    9.0,
                    8.0,
                    7.0,
                    6.0,
                    5.0,
                    4.0,
                    3.0,
                    2.0,
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ]
            ),
        )
        connection.act(t_point=4, postsynaptic_index=0, psp_waveforms=psp_waveforms)
        assert np.array_equal(
            psp_waveforms[0],
            np.array(
                [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    8.0,
                    12.0,
                    16.0,
                    17.0,
                    18.0,
                    16.0,
                    14.0,
                    12.0,
                    10.0,
                    8.0,
                    6.0,
                    4.0,
                    2.0,
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ]
            ),
        )
        connection.act(t_point=40, postsynaptic_index=0, psp_waveforms=psp_waveforms)
        assert np.array_equal(
            psp_waveforms[0],
            np.array(
                [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    8.0,
                    12.0,
                    16.0,
                    17.0,
                    18.0,
                    16.0,
                    14.0,
                    12.0,
                    10.0,
                    8.0,
                    6.0,
                    4.0,
                    2.0,
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    6.0,
                    8.0,
                    10.0,
                ]
            ),
        )
        connection.act(t_point=50, postsynaptic_index=0, psp_waveforms=psp_waveforms)
        assert np.array_equal(
            psp_waveforms[0],
            np.array(
                [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    8.0,
                    12.0,
                    16.0,
                    17.0,
                    18.0,
                    16.0,
                    14.0,
                    12.0,
                    10.0,
                    8.0,
                    6.0,
                    4.0,
                    2.0,
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    2.0,
                    4.0,
                    6.0,
                    8.0,
                    10.0,
                ]
            ),
        )


if __name__ == "__main__":
    connection_tests = TestConnection()
    connection_tests.test_connection_psp()
    connection_tests.test_connection_act()
